
--- 
db: 
  connection: connection-string-from-config-server
  host: "127.0.0.1"
  port: 1200
my: 
  greetings: "Hello world from config server"
  list: 
    values: "One, Two, Server"


server:
  port: 8088